operators:
  amqs-operator0:
    enabled: true
    namespace:
      name: amqtest
    subscription:
      channel: amq-streams-2.5.x
      approval: Manual
      operatorName: amq-streams
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      csv: amq-streams-v2.5.1-2
    kafka:
      user_prefix: user-info
      version: "3.5.0"
      protocol_version: "3.5"
      replicas: 1
      min_replicas: 1
      storage: 10Gi
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
    zookeeper:
      replicas: 1
      storage: 10Gi
      limits:
        cpu: "0.5"
        memory: 1Gi
      requests:
        cpu: "0.5"
        memory: 1Gi
